(module): "Masters"
(cs_namespace): "ReceivableAccounts"
(namespace): "Financial"

(database_name): "ERP_FMS"
(schema_name): "Maestro"

TrialBalanceFilter:
  (sql_ignore): true
  (filter_ignore): true
  (dao_ignore): true
  (service_ignore): true
  (list_ignore): true
  (embedFilter): true

  page: { type: number, default: 1, (alt): NumeroPagina }
  pageSize: { type: number, default: 5, (alt): CandidadRegistros }
  initDate: { type: date, default: zeroDate(), (alt): FechaInicio }
  endDate: { type: date, default: now(), (alt): FechaFin }
  initAccountingAccount: { default: "", type: string, (alt): CodigoCuentaContableInicio }
  endAccountingAccount: { default: "", type: string, (alt): CodigoCuentaContableFin }
  detailLevel: { default: -1, type: long, (alt): IdNivelDetalle }
  idBusiness: { default: 1, type: long, (alt): IdEmpresa }

TrialBalanceElement:
  (service_ignore): true
  (sql_ignore): true
  (filter_ignore): true

  fiscalPeriodId: { type: long, (alt): IdPeriodoFiscal }
  accountingAccountId: { type: long, (alt): IdCuentaContable }
  accountingAccountCode: { type: string, (alt): CodigoCuentaContable, (display): Código de la cuenta }
  accountingAccountName: { type: string, (alt): CuentaContable, (display): Descripción de la cuenta }
  previousBalance: { type: double, (alt): SaldoAnterior, (display): Saldo anterior }
  credit: { type: double, (alt): Credito, (display): Creditos }
  debit: { type: double, (alt): Debito, (display): Debitos }

TrialBalance:
  (alt): "BalanceComprobacion"
  (list_ignore): true
  (isPage): true
  (notPost): true
  (singular): true
  (singularFromFilter): true
  (filter): TrialBalanceFilter
  (pageItem): TrialBalanceElement

  elements: { type: TrialBalanceElement, array: true, (alt): ELEMENTOS }
  count: { type: number, (alt): CantidadRegistros }

##############################################################################################################

LedgerBalanceFilter:
  (sql_ignore): true
  (service_ignore): true
  (list_ignore): true

  initDate: { type: date, default: zeroDate(), (alt): FechaInicio }
  endDate: { type: date, default: now(), (alt): FechaFin }
  initAccountingAccount: { default: "", type: string, (alt): CodigoCuentaContableInicio }
  endAccountingAccount: { default: "", type: string, (alt): CodigoCuentaContableFin }
  idBusiness: { default: 1, type: long, (alt): IdEmpresa }

LedgerBalanceItem:
  (sql_ignore): true
  (filter_ignore): true
  (service_ignore): true
  (list_ignore): true

  fiscalPeriodId: { type: long, (alt): IdPeriodoFiscal }
  accountingAccountId: { type: long, (alt): IdCuentaContable }
  accountingAccountName: { type: string, (alt): CuentaContable }
  accountingAccountCode: { type: string, (alt): CodigoCuentaContable }
  credit: { type: double, (alt): Credito }
  debit: { type: double, (alt): Debito }

IncomeStatement:
  (filter): LedgerBalanceFilter
  (alt): EstadoResultado
  (list_ignore): true
  (singular): true
  (singularFromFilter): true
  (notPost): true

  (spGet): "[ERP_FMS].[Transaccional].[spObtenerEstadoResultado]"

  incomeRoot: { type: LedgerBalanceItem, array: true, (alt): DETALLEPASIVO }
  expenseRoot: { type: LedgerBalanceItem, array: true, (alt): DETALLEPATRIMONIO }
  # incomeRoot: { type: IncomeStatementDistribution, array: true, (alt): DETALLEINGRESOS }
  # expenseRoot: { type: IncomeStatementDistribution, array: true, (alt): DETALLEEGRESOS }

GeneralBalance:
  (filter): LedgerBalanceFilter
  (alt): BalanceGeneral
  # (list_ignore): true
  (singular): true
  (singularFromFilter): true
  (notPost): true

  (spGet): "[ERP_FMS].[Transaccional].[spObtenerBalanceGeneral]"

  activeRoot: { type: LedgerBalanceItem, array: true, (alt): DETALLEACTIVO }
  pasiveRoot: { type: LedgerBalanceItem, array: true, (alt): DETALLEPASIVO }
  equityRoot: { type: LedgerBalanceItem, array: true, (alt): DETALLEPATRIMONIO }

# FiscalYearFilter:
#   (sql_ignore): true
#   (filter_ignore): true
#   (dao_ignore): true
#   (service_ignore): true

#   id:
#     type: long
#     pk: true
#     (alt): "IdPeriodoFiscal"
#     default: -1
#   year: text
#   unitPeriodType: long
#   fiscalPeriods: { type: FiscalPeriod, array: true }
#   active: bool

# FiscalYear:
#   (display): Ejercicio fiscal
#   (displayPlural): Ejercicios fiscales
#   (filter): FiscalYearFilter
#   (alt): EjercicioFiscal
#   id:
#     type: long
#     pk: true
#     (alt): "IdPeriodoFiscal"
#     default: -1
#     (display): Código
#   year: { type: text, (display): Ejercicio Fiscal }
#   periodLength: { type: number, (display): Cantidad de periodos }
#   initDate: { type: date, default: "now()", (display): Fecha de inicio }
#   zeroDate: { type: date, default: "zeroDate()", (alt): "FechaFin", (display): Fecha fin}
#   unitPeriodTypeId: long
#   unitPeriodType: string
#   fiscalPeriods: { type: FiscalPeriod, array: true }
#   active: { type: bool, (active): true }
#   createdByUserId: long
#   updatedByUserId: long
#   createdByUser: { type: string, (display): Creado por }
#   updatedByUser: { type: string, (display): Actualizado por }

# FiscalPeriod:
#   (alt): PeriodoFiscal
#   id:
#     type: long
#     pk: true
#   periodNumber: number
#   name: string
#   range: string
#   initDate: date
#   endDate: date
#   openedModules: { type: FiscalPeriodModule, array: true }
#   closedModules: { type: FiscalPeriodModule, array: true }
#   indClosed: string
#   active: bool
#   createdByUserId: long
#   updatedByUserId: long
#   createdByUser: string
#   updatedByUser: string
#   (service_ignore): true

# FiscalPeriodModule:
#   (alt): PeriodoFiscalModulo
#   id:
#     type: long
#     pk: true
#   name: string
#   indClosed: number
#   (service_ignore): true
